# permissions for end users to view tankareleases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tankarelease-viewer-role
rules:
- apiGroups:
  - tanka.toolkit.fluxcd.io
  resources:
  - tankareleases
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tanka.toolkit.fluxcd.io
  resources:
  - tankareleases/status
  verbs:
  - get
